SOCCER_BROADCAST_BADLIST = [
    "Antenna 20 Years",
    "CL beIN Sports English SD in Spanish",
    "ESPN Deportes",
    "ESPN Deportes HD",
    "ESPN3",
    "Fox Deportes",
    "Fox Deportes HD",
    "Fox Soccer Plus",
    "Fox Soccer Plus HD",
    "Fox Sports 2 HD",
    "GOL TV",
    "NBC Sports California SAT",
    "NBC Sports California SAT HD",
    "NBCSports.com",
    "Nuestra Tele Internacional",
    "RREC",
    "SporTV",
    "TUDN",
    "TV5MONDE Etats Unis",
    "Telemundo Satellite Feed",
    "Telemundo Satellite Feed Pacific",
    "Twitch",
    "TyC Sports Internacional USA",
    "UniMas",
    "UniMas Satellite Feed (Pacific)",
    "Univision NOW",
    "Univision Network",
    "VIX+",
    "ViX",
    "Yes Network",
    "Yes Network HD",
    "beIN Sports",
    "beIN Sports En Español",
    "beIN Sports En Español HD",
    "beIN Sports HD",
    "iFollow",
]

BROADCAST_GOODLIST = [
    "CBS",
    "CBS Sports Network",
    "CBS Sports Network HD",
    "ESPN+ USA",
    "FS2",
    "NBC",
    "NBC Sports Chicago",
    "NBC Sports Chicago HD",
    "Paramount+",
    "Peacock",
    "TNT",
    "TNT HD",
    "TNT HD (Pacific)",
    "Telemundo Television Network",
    "UNIVERSO",
    "UNIVERSO HD",
    "USA Network",
    "USA Network HD",
]
