from shared import ElligibleSportsEnum, FavoriteCriterion


INDYCAR_CHANNEL_GOODLIST = [
    "NBC",
    "USA Net",
    "Peacock",
]

F1_CHANNEL_GOODLIST = [
    "ESPN",
    "ESPN2",
    "ABC",
]

MLB_BROADCAST_BADLIST = [
    "KOA 850 AM/94.1 FM ",
    "WMMS 100.7",
    "WTAM 1100",
    "Bally Sports Southwest Extra",
    "Bally Sports Kansas City",
    "NESN",
    "KNBR 680",
    "98.7 FM Arizona's Sports Station",
    "SNET",
    "Bally Deportes San Diego",
    "WFAN 660/101.9 FM",
    "Bally Sports Sun",
    "MLB.TV",
    "Bally Sports South",
    "Bally Sports Southwest",
    "97.1 The Ticket",
    "NBCS BA",
    "SportsNet LA",
    "Bally Sports San Diego",
    "A's Cast",
    "Amazon Prime Video",
    "WLW 700",
    "WEEI 850",
    "NBC Sports App",
    "KBME 790 (delay)",
    "Bally Sports Arizona",
    "SNY",
    "WJFK 106.7 The Fan",
    "Bally Sports Great Lakes",
    "WDAE 620 AM/95.3 FM",
    "KWOD 1660",
    "ATT SportsNet-SW",
    "NBCSP+",
    "ATT SportsNet-RM",
    "YES",
    "Marquee Sports Network",
    "MLB.com",
    "WTMJ 620",
    "670 The Score",
    "Bally Sports SoCal",
    "WAQI 710",
    "NESN+",
    "Audacy",
    "WBAL NewsRadio AM/FM/ HD2 97.9 ",
    "Bally Sports Midwest",
    "Dodgers Radio AM570",
    "NBCSP",
    "KTNQ 1020",
    "MLBN (out-of-market only)",
    "KDKA-FM 93.7",
    "WMVP 1000 AM",
    "KLAA 830",
    "The Wolf 102.9 FM",
    "ROOTNW",
    "WEEI 93.7",
    "SN590",
    "Braves Radio Network",
    "KCSP 610",
    "WXYT 1270",
    "WCNN 680/93.7",
    "NBCSCH+",
    "1510 AM - KSFN",
    "WCBS 880",
    "WSAI-1360",
    "KIRO 710",
    "Bally Sports Florida",
    "Bloomberg 960 AM",
    "KWFN 97.3",
    "Bally Sports Detroit",
    "Bally Sports Ohio",
    "KCOP",
    "The Team 980",
    "Bally Sports Wisconsin",
    "NBCSCA",
    "NESN 360",
    "FOX Sports 940AM (WINZ)",
    "REAL 106.1",
    "Bally Sports Southeast",
    "Cardinals Radio Network",
    "Bally Sports North",
    "ROOTNW+",
    "Bally Sports West",
    "WPIX",
    "KMOX 1120 AM/98.7 FM",
    "TIBN",
    "94 WIP",
    "TVA Sports",
    "ESPN Phoenix 620",
    "105.3 The Fan",
    "WCCO 830",
    "WIFN 1340 AM/103.7FM",
    "KIRO 710 (delay)",
    "Brewers Radio Network",
    "94.5 ESPN Milwaukee",
    "KBME 790 AM/94.5 FM HD-2",
    "100.1 FM/KDKA-AM 1020",
    "ATT SportsNet-PIT",
    "MASN",
    "98 Rock FM/HD2 97.9, WBAL NewsRadio AM/FM",
    "Sportsnet.ca",
    "SNET NOW App",
    "KHOV Univision 105.1",
    "KIQI 1010",
]

NHL_BROADCAST_BADLIST = [
    "BSSC",
    "NBCSCH+",
    "BSSW",
    "KCOP-13",
    "ALT",
    "SN360",
    "TSN4",
    "SN1",
    "SNW",
    "BSSUNX",
    "BSNX",
    "RDS",
    "BSWIX",
    "NHLN",
    "BSOH",
    "MSGSN2",
    "KONG",
    "BSSUN",
    "SNOL",
    "SNE",
    "TSN3",
    "CBC",
    "BSSWX",
    "NBCSWA",
    "ATTSN-RM",
    "MSG-B",
    "BSMW",
    "SN",
    "NHLN (JIP)",
    "BSDETX",
    "BSWI",
    "MSGSN",
    "NBCSCA",
    "ATTSN-PT",
    "BSN",
    "MSG 2",
    "BSAZX",
    "BSDET",
    "SNW (JIP)",
    "BSAZ",
    "TSN5",
    "CITY",
    "RDS2",
    "ALT2",
    "BSFLX",
    "SNO",
    "BSMW APP",
    "TVAS",
    "TVAS2",
    "SNP",
    "NBCSWA+",
    "SNF",
    "BSW",
    "MSG",
    "BSFL",
    "KTNV",
    "ROOT-NW",
    "TSN2",
    "RDSI",
    "NESN",
    "NBCSP+",
    "BSSO",
    "NBCSP",
]

SOCCER_BROADCAST_BADLIST = [
    "Antenna 20 Years",
    "CL beIN Sports English SD in Spanish",
    "DAZN USA",
    "ESPN Deportes",
    "ESPN Deportes HD",
    "ESPN3",
    "ESPN 3",
    "Fox Deportes",
    "Fox Deportes HD",
    "Fox Soccer Plus",
    "Fox Soccer Plus HD",
    "Fox Sports 2 HD",
    "GOL TV",
    "In Demand PPVHD (HD Events)",
    "MLS Season Pass on Apple TV",
    "NBC Sports California SAT",
    "NBC Sports California SAT HD",
    "NBCSports.com",
    "Nuestra Tele Internacional",
    "RREC",
    "RTPi RadioTV Portuguesa Int'l",
    "SporTV",
    "TUDN",
    "TV5MONDE Etats Unis",
    "Telemundo Satellite Feed",
    "Telemundo Satellite Feed Pacific",
    "Twitch",
    "TyC Sports Internacional USA",
    "UniMas",
    "UniMas Satellite Feed (Pacific)",
    "Univision NOW",
    "Univision Network",
    "VIX+",
    "ViX",
    "Yes Network",
    "Yes Network HD",
    "beIN Sports",
    "beIN Sports En Español",
    "beIN Sports En Español HD",
    "beIN Sports HD",
    "iFollow",
]

BROADCAST_GOODLIST = [
    "CBS",
    "CBS Sports Network",
    "CBS Sports Network HD",
    "ESPN+ USA",
    "FS2",
    "NBC",
    "NBC Sports Chicago",
    "NBC Sports Chicago HD",
    "Paramount+",
    "Peacock",
    "TNT",
    "TNT HD",
    "TNT HD (Pacific)",
    "Telemundo Television Network",
    "UNIVERSO",
    "UNIVERSO HD",
    "USA Network",
    "USA Network HD",
]

NATIONAL_FLAGS = {
    "Ascension Island": "🇦🇨",
    "Andorra": "🇦🇩",
    "United Arab Emirates": "🇦🇪",
    "Afghanistan": "🇦🇫",
    "Antigua & Barbuda": "🇦🇬",
    "Anguilla": "🇦🇮",
    "Albania": "🇦🇱",
    "Armenia": "🇦🇲",
    "Angola": "🇦🇴",
    "Antarctica": "🇦🇶",
    "Argentina": "🇦🇷",
    "American Samoa": "🇦🇸",
    "Austria": "🇦🇹",
    "Australia": "🇦🇺",
    "Aruba": "🇦🇼",
    "Åland Islands": "🇦🇽",
    "Azerbaijan": "🇦🇿",
    "Bosnia & Herzegovina": "🇧🇦",
    "Barbados": "🇧🇧",
    "Bangladesh": "🇧🇩",
    "Belgium": "🇧🇪",
    "Burkina Faso": "🇧🇫",
    "Bulgaria": "🇧🇬",
    "Bahrain": "🇧🇭",
    "Burundi": "🇧🇮",
    "Benin": "🇧🇯",
    "St. Barthélemy": "🇧🇱",
    "Bermuda": "🇧🇲",
    "Brunei": "🇧🇳",
    "Bolivia": "🇧🇴",
    "Caribbean Netherlands": "🇧🇶",
    "Brazil": "🇧🇷",
    "Bahamas": "🇧🇸",
    "Bhutan": "🇧🇹",
    "Bouvet Island": "🇧🇻",
    "Botswana": "🇧🇼",
    "Belarus": "🇧🇾",
    "Belize": "🇧🇿",
    "Canada": "🇨🇦",
    "Cocos (Keeling) Islands": "🇨🇨",
    "Congo - Kinshasa": "🇨🇩",
    "Central African Republic": "🇨🇫",
    "Congo - Brazzaville": "🇨🇬",
    "Switzerland": "🇨🇭",
    "Côte d’Ivoire": "🇨🇮",
    "Cook Islands": "🇨🇰",
    "Chile": "🇨🇱",
    "Cameroon": "🇨🇲",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Clipperton Island": "🇨🇵",
    "Costa Rica": "🇨🇷",
    "Cuba": "🇨🇺",
    "Cape Verde": "🇨🇻",
    "Curaçao": "🇨🇼",
    "Christmas Island": "🇨🇽",
    "Cyprus": "🇨🇾",
    "Czechia": "🇨🇿",
    "Germany": "🇩🇪",
    "Diego Garcia": "🇩🇬",
    "Djibouti": "🇩🇯",
    "Denmark": "🇩🇰",
    "Dominica": "🇩🇲",
    "Dominican Republic": "🇩🇴",
    "Algeria": "🇩🇿",
    "Ceuta & Melilla": "🇪🇦",
    "Ecuador": "🇪🇨",
    "Estonia": "🇪🇪",
    "Egypt": "🇪🇬",
    "Western Sahara": "🇪🇭",
    "Eritrea": "🇪🇷",
    "Spain": "🇪🇸",
    "Ethiopia": "🇪🇹",
    "European Union": "🇪🇺",
    "Finland": "🇫🇮",
    "Fiji": "🇫🇯",
    "Falkland Islands": "🇫🇰",
    "Micronesia": "🇫🇲",
    "Faroe Islands": "🇫🇴",
    "France": "🇫🇷",
    "Gabon": "🇬🇦",
    "United Kingdom": "🇬🇧",
    "Grenada": "🇬🇩",
    "Georgia": "🇬🇪",
    "French Guiana": "🇬🇫",
    "Guernsey": "🇬🇬",
    "Ghana": "🇬🇭",
    "Gibraltar": "🇬🇮",
    "Greenland": "🇬🇱",
    "Gambia": "🇬🇲",
    "Guinea": "🇬🇳",
    "Guadeloupe": "🇬🇵",
    "Equatorial Guinea": "🇬🇶",
    "Greece": "🇬🇷",
    "South Georgia & South Sandwich Islands": "🇬🇸",
    "Guatemala": "🇬🇹",
    "Guam": "🇬🇺",
    "Guinea-Bissau": "🇬🇼",
    "Guyana": "🇬🇾",
    "Hong Kong SAR China": "🇭🇰",
    "Heard & McDonald Islands": "🇭🇲",
    "Honduras": "🇭🇳",
    "Croatia": "🇭🇷",
    "Haiti": "🇭🇹",
    "Hungary": "🇭🇺",
    "Canary Islands": "🇮🇨",
    "Indonesia": "🇮🇩",
    "Ireland": "🇮🇪",
    "Israel": "🇮🇱",
    "Isle of Man": "🇮🇲",
    "India": "🇮🇳",
    "British Indian Ocean Territory": "🇮🇴",
    "Iraq": "🇮🇶",
    "Iran": "🇮🇷",
    "Iceland": "🇮🇸",
    "Italy": "🇮🇹",
    "Jersey": "🇯🇪",
    "Jamaica": "🇯🇲",
    "Jordan": "🇯🇴",
    "Japan": "🇯🇵",
    "Kenya": "🇰🇪",
    "Kyrgyzstan": "🇰🇬",
    "Cambodia": "🇰🇭",
    "Kiribati": "🇰🇮",
    "Comoros": "🇰🇲",
    "St. Kitts & Nevis": "🇰🇳",
    "North Korea": "🇰🇵",
    "South Korea": "🇰🇷",
    "Kuwait": "🇰🇼",
    "Cayman Islands": "🇰🇾",
    "Kazakhstan": "🇰🇿",
    "Laos": "🇱🇦",
    "Lebanon": "🇱🇧",
    "St. Lucia": "🇱🇨",
    "Liechtenstein": "🇱🇮",
    "Sri Lanka": "🇱🇰",
    "Liberia": "🇱🇷",
    "Lesotho": "🇱🇸",
    "Lithuania": "🇱🇹",
    "Luxembourg": "🇱🇺",
    "Latvia": "🇱🇻",
    "Libya": "🇱🇾",
    "Morocco": "🇲🇦",
    "Monaco": "🇲🇨",
    "Moldova": "🇲🇩",
    "Montenegro": "🇲🇪",
    "St. Martin": "🇲🇫",
    "Madagascar": "🇲🇬",
    "Marshall Islands": "🇲🇭",
    "North Macedonia": "🇲🇰",
    "Mali": "🇲🇱",
    "Myanmar (Burma)": "🇲🇲",
    "Mongolia": "🇲🇳",
    "Macao Sar China": "🇲🇴",
    "Northern Mariana Islands": "🇲🇵",
    "Martinique": "🇲🇶",
    "Mauritania": "🇲🇷",
    "Montserrat": "🇲🇸",
    "Malta": "🇲🇹",
    "Mauritius": "🇲🇺",
    "Maldives": "🇲🇻",
    "Malawi": "🇲🇼",
    "Mexico": "🇲🇽",
    "Malaysia": "🇲🇾",
    "Mozambique": "🇲🇿",
    "Namibia": "🇳🇦",
    "New Caledonia": "🇳🇨",
    "Niger": "🇳🇪",
    "Norfolk Island": "🇳🇫",
    "Nigeria": "🇳🇬",
    "Nicaragua": "🇳🇮",
    "Netherlands": "🇳🇱",
    "Norway": "🇳🇴",
    "Nepal": "🇳🇵",
    "Nauru": "🇳🇷",
    "Niue": "🇳🇺",
    "New Zealand": "🇳🇿",
    "Oman": "🇴🇲",
    "Panama": "🇵🇦",
    "Peru": "🇵🇪",
    "French Polynesia": "🇵🇫",
    "Papua New Guinea": "🇵🇬",
    "Philippines": "🇵🇭",
    "Pakistan": "🇵🇰",
    "Poland": "🇵🇱",
    "St. Pierre & Miquelon": "🇵🇲",
    "Pitcairn Islands": "🇵🇳",
    "Puerto Rico": "🇵🇷",
    "Palestinian Territories": "🇵🇸",
    "Portugal": "🇵🇹",
    "Palau": "🇵🇼",
    "Paraguay": "🇵🇾",
    "Qatar": "🇶🇦",
    "Réunion": "🇷🇪",
    "Romania": "🇷🇴",
    "Serbia": "🇷🇸",
    "Russia": "🇷🇺",
    "Rwanda": "🇷🇼",
    "Saudi Arabia": "🇸🇦",
    "Solomon Islands": "🇸🇧",
    "Seychelles": "🇸🇨",
    "Sudan": "🇸🇩",
    "Sweden": "🇸🇪",
    "Singapore": "🇸🇬",
    "St. Helena": "🇸🇭",
    "Slovenia": "🇸🇮",
    "Svalbard & Jan Mayen": "🇸🇯",
    "Slovakia": "🇸🇰",
    "Sierra Leone": "🇸🇱",
    "San Marino": "🇸🇲",
    "Senegal": "🇸🇳",
    "Somalia": "🇸🇴",
    "Suriname": "🇸🇷",
    "South Sudan": "🇸🇸",
    "São Tomé & Príncipe": "🇸🇹",
    "El Salvador": "🇸🇻",
    "Sint Maarten": "🇸🇽",
    "Syria": "🇸🇾",
    "Eswatini": "🇸🇿",
    "Tristan Da Cunha": "🇹🇦",
    "Turks & Caicos Islands": "🇹🇨",
    "Chad": "🇹🇩",
    "French Southern Territories": "🇹🇫",
    "Togo": "🇹🇬",
    "Thailand": "🇹🇭",
    "Tajikistan": "🇹🇯",
    "Tokelau": "🇹🇰",
    "Timor-Leste": "🇹🇱",
    "Turkmenistan": "🇹🇲",
    "Tunisia": "🇹🇳",
    "Tonga": "🇹🇴",
    "Turkey": "🇹🇷",
    "Trinidad & Tobago": "🇹🇹",
    "Tuvalu": "🇹🇻",
    "Taiwan": "🇹🇼",
    "Tanzania": "🇹🇿",
    "Ukraine": "🇺🇦",
    "Uganda": "🇺🇬",
    "U.S. Outlying Islands": "🇺🇲",
    "United Nations": "🇺🇳",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Vatican City": "🇻🇦",
    "St. Vincent & Grenadines": "🇻🇨",
    "Venezuela": "🇻🇪",
    "British Virgin Islands": "🇻🇬",
    "U.S. Virgin Islands": "🇻🇮",
    "Vietnam": "🇻🇳",
    "Vanuatu": "🇻🇺",
    "Wallis & Futuna": "🇼🇫",
    "Samoa": "🇼🇸",
    "Kosovo": "🇽🇰",
    "Yemen": "🇾🇪",
    "Mayotte": "🇾🇹",
    "South Africa": "🇿🇦",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
}

MLB_FAVORITE_CRITERIA: list[FavoriteCriterion] = [
    {"property": "matchup", "comparison": "contains", "value": "Red Sox"},
]

NBA_FAVORITE_CRITERIA: list[FavoriteCriterion] = [
    {
        "property": "sport",
        "comparison": "equals",
        "value": ElligibleSportsEnum.NBA.value,
    },
]

NCAA_TOURNAMENT_FAVORITE_CRITERIA: list[FavoriteCriterion] = [
    {
        "property": "sport",
        "comparison": "equals",
        "value": ElligibleSportsEnum.BASKETBALL.value,
    },
]

NHL_FAVORITE_CRITERIA: list[FavoriteCriterion] = [
    {"property": "matchup", "comparison": "contains", "value": "Bruins"},
]


SOCCER_FAVORITE_CRITERIA: list[FavoriteCriterion] = [
    {"property": "league", "comparison": "equals", "value": "Premier League 🏴󠁧󠁢󠁥󠁮󠁧󠁿"},
    {"property": "league", "comparison": "equals", "value": "MLS 🇺🇸"},
    {"property": "league", "comparison": "equals", "value": "Champions League"},
    {"property": "league", "comparison": "equals", "value": "EURO"},
    {"property": "matchup", "comparison": "contains", "value": "Indy Eleven"},
]
